[build-system]
requires = ["maturin>=1.5,<2.0"]
build-backend = "maturin"

[project]
name = "taskchampion-py"
version = "3.0.1.1"
requires-python = ">=3.9"
classifiers = [
    "Programming Language :: Rust",
    "Programming Language :: Python :: Implementation :: CPython",
    "Programming Language :: Python :: Implementation :: PyPy",
]
authors = [
    {name = "Illya Laifu", email="illyalaifu@gmail.com"},
    {name = "Dustin J. Mitchell", email="dustin@v.igoro.us"},
]
license = {file = "LICENSE"}
readme = "README.md"

[project.urls]
homepage = "https://gothenburgbitfactory.org/taskchampion"
repository = "https://github.com/GothenburgBitFactory/taskchampion-py"
changelog = "https://github.com/GothenburgBitFactory/taskchampion-py/releases"

[tool.maturin]
features = ["pyo3/extension-module", "server-local"]

[tool.poetry]
name = "taskchampion-py"
version = "0.1.0"
authors = ["illyalaifu <illyalaifu@gmail.com>"]
description = ""
package-mode = false

[tool.poetry.dependencies]
python = ">=3.9"
maturin = { extras = ["patchelf"], version = "^1.5.1" }

[tool.poetry.group.test.dependencies]
pytest = "^8.2.0"
mypy = "^1.10.0"

[tool.black]
line-length = 88
target-version = ['py39']
include = '\.pyi?$'
