from collections.abc import Iterator
from datetime import datetime
from enum import Enum
from typing import final, overload

__all__ = [
    "Replica",
    "Operation",
    "Operations",
    "Status",
    "TaskData",
    "Task",
    "WorkingSet",
    "Annotation",
    "Tag",
    "DependencyMap",
    "AccessMode",
]

@final
class AccessMode(Enum):
    ReadWrite = 1
    ReadOnly = 2

@final
class Replica:
    @staticmethod
    def new_on_disk(
        path: str,
        create_if_missing: bool,
        access_mode: AccessMode = AccessMode.ReadWrite,
    ) -> Replica: ...
    @staticmethod
    def new_in_memory() -> Replica: ...
    def create_task(self, uuid: str, ops: Operations) -> Task: ...
    def all_task_uuids(self) -> list[str]: ...
    def all_tasks(self) -> dict[str, Task]: ...
    def all_task_data(self) -> dict[str, TaskData]: ...
    def pending_tasks(self) -> list[Task]: ...
    def pending_task_data(self) -> list[TaskData]: ...
    def working_set(self) -> WorkingSet: ...
    def dependency_map(self, force: bool) -> DependencyMap: ...
    def get_task(self, uuid: str) -> Task | None: ...
    def get_task_data(self, uuid: str) -> TaskData | None: ...
    def get_task_operations(self, uuid: str) -> Operations: ...
    def get_undo_operations(self) -> Operations: ...
    def expire_tasks(self) -> None: ...
    def sync_to_local(self, server_dir: str, avoid_snapshots: bool) -> None: ...
    def sync_to_remote(
        self, url: str, client_id: str, encryption_secret: str, avoid_snapshots: bool
    ) -> None: ...
    def sync_to_gcp(
        self,
        bucket: str,
        credential_path: str | None,
        encryption_secret: str,
        avoid_snapshots: bool,
    ) -> None: ...
    def rebuild_working_set(self, renumber: bool) -> None: ...
    def num_local_operations(self) -> int: ...
    def num_undo_points(self) -> int: ...
    def commit_operations(self, ops: Operations) -> None: ...
    def commit_reversed_operations(self, operations: Operations) -> bool: ...

@final
class Operation:
    @staticmethod
    def Create(uuid: str) -> Operation: ...
    @staticmethod
    def Delete(uuid: str, old_task: dict[str, str]) -> Operation: ...
    @staticmethod
    def Update(
        uuid: str,
        property: str,
        timestamp: datetime,
        old_value: str | None = None,
        value: str | None = None,
    ) -> Operation: ...
    @staticmethod
    def UndoPoint() -> Operation: ...
    def is_create(self) -> bool: ...
    def is_update(self) -> bool: ...
    def is_delete(self) -> bool: ...
    def is_undo_point(self) -> bool: ...

    uuid: str
    old_task: dict[str, str]
    timestamp: datetime
    property: str | None
    old_value: str | None
    value: str | None

@final
class Operations:
    def __new__(cls) -> Operations: ...
    def append(self, op: Operation) -> None: ...
    def __len__(self) -> int: ...
    @overload
    def __getitem__(self, i: int, /) -> Operation: ...
    @overload
    def __getitem__(self, s: slice, /) -> Operations: ...
    def __iter__(self) -> Iterator[Operation]: ...

@final
class Status(Enum):
    Pending = 1
    Completed = 2
    Deleted = 3
    Recurring = 4
    Unknown = 5

@final
class TaskData:
    @staticmethod
    def create(uuid: str, ops: Operations) -> TaskData: ...
    def get_uuid(self) -> str: ...
    def get(self, /, value: str) -> str | None: ...
    def has(self, /, value: str) -> bool: ...
    def properties(self) -> list[str]: ...
    def items(self) -> list[tuple[str, str]]: ...
    def update(self, property: str, value: str | None, ops: Operations) -> None: ...
    def delete(self, ops: Operations) -> None: ...

@final
class Task:
    def get_uuid(self) -> str: ...
    def get_status(self) -> Status: ...
    def get_entry(self) -> datetime | None: ...
    def get_priority(self) -> str: ...
    def get_wait(self) -> datetime | None: ...
    def get_description(self) -> str: ...
    def is_waiting(self) -> bool: ...
    def is_active(self) -> bool: ...
    def is_blocked(self) -> bool: ...
    def is_blocking(self) -> bool: ...
    def has_tag(self, tag: Tag) -> bool: ...
    def get_tags(self) -> list[Tag]: ...
    def get_annotations(self) -> list[Annotation]: ...
    def get_user_defined_attribute(self, key: str) -> str | None: ...
    def get_user_defined_attributes(self) -> list[tuple[str, str]]: ...
    def get_modified(self) -> datetime | None: ...
    def get_due(self) -> datetime | None: ...
    def get_dependencies(self) -> list[str]: ...
    def get_value(self, property: str) -> str | None: ...
    def set_status(self, status: Status, ops: Operations) -> None: ...
    def set_description(self, description: str, ops: Operations) -> None: ...
    def set_priority(self, priority: str, ops: Operations) -> None: ...
    def set_entry(self, entry: datetime | None, ops: Operations) -> None: ...
    def set_wait(self, wait: datetime | None, ops: Operations) -> None: ...
    def set_modified(self, modified: datetime, ops: Operations) -> None: ...
    def set_value(self, property: str, value: str | None, ops: Operations) -> None: ...
    def start(self, ops: Operations) -> None: ...
    def stop(self, ops: Operations) -> None: ...
    def done(self, ops: Operations) -> None: ...
    def add_tag(self, tag: Tag, ops: Operations) -> None: ...
    def remove_tag(self, tag: Tag, ops: Operations) -> None: ...
    def add_annotation(self, annotation: Annotation, ops: Operations) -> None: ...
    def remove_annotation(self, timestamp: datetime, ops: Operations) -> None: ...
    def set_due(self, due: datetime | None, ops: Operations) -> None: ...
    def set_user_defined_attribute(
        self, key: str, value: str, ops: Operations
    ) -> None: ...
    def remove_user_defined_attribute(self, key: str, ops: Operations) -> None: ...
    def add_dependency(self, dep: str, ops: Operations) -> None: ...
    def remove_dependency(self, dep: str, ops: Operations) -> None: ...
    def to_task_data(self) -> TaskData: ...

@final
class WorkingSet:
    def __len__(self) -> int: ...
    def largest_index(self) -> int: ...
    def is_empty(self) -> bool: ...
    def by_index(self, index: int) -> str | None: ...
    def by_uuid(self, uuid: str) -> int | None: ...
    def __iter__(self) -> Iterator[tuple[int, str]]: ...

@final
class Annotation:
    entry: datetime
    description: str

    def __new__(cls, entry: datetime, description: str) -> Annotation: ...

@final
class DependencyMap:
    def dependencies(self, dep_of: str) -> list[str]: ...
    def dependents(self, dep_on: str) -> list[str]: ...

@final
class Tag:
    def __new__(cls, tag: str) -> Tag: ...
    def is_synthetic(self) -> bool: ...
    def is_user(self) -> bool: ...
