name: checks

on:
  push:
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  clippy:
    runs-on: ubuntu-latest
    name: "Check & Clippy"

    steps:
      - uses: actions/checkout@v4

      - name: Cache cargo registry
        uses: actions/cache@v4
        with:
          path: ~/.cargo/registry
          key: ${{ runner.os }}-cargo-registry-${{ hashFiles('**/Cargo.lock') }}

      - name: Cache cargo build
        uses: actions/cache@v4
        with:
          path: target
          key: ${{ runner.os }}-cargo-build-target-${{ hashFiles('**/Cargo.lock') }}

      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: "1.91.1" # MSRV
          components: clippy

      - name: Check
        run: cargo check

      - name: Clippy
        run: cargo clippy --all-features --no-deps -- -D warnings

  fmt:
    runs-on: ubuntu-latest
    name: "Rust Formatting"
    steps:
      - uses: actions/checkout@v4

      - uses: dtolnay/rust-toolchain@master
        with:
          components: rustfmt
          toolchain: "1.91.1"

      - name: Rustfmt
        run: cargo fmt --all -- --check

  black:
    runs-on: ubuntu-latest
    name: "Python Formatting"
    steps:
      - uses: actions/checkout@v4
      - uses: psf/black@stable
